### PR TITLE
Contrast 26745

### PR DESCRIPTION
**Pull request by serge17**
Implemented a new workflow for the settings page.

### CODE REVIEW

**Comment by gmoore** [comment]
Looking great! 

* Change "UUID" label to "Organization ID"
* Can you verify this: add an org, view vulnerabilities pane, add another org, new org's applications are available in the filter
* Remove the "Restore Defaults" and "Apply" buttons
* When I Removed an org, that org's applications were still available for filtering.

**Comment by gmoore** [comment]
✅ Buttons removed
✅ Label text

**Comment by gmoore** [comment]
I removed all orgs, then just added one, and I think we're stuck on this error message

error

**Comment by serge17** [comment]
@gmoore Any exception is thrown in the logs?

**Comment by rduran0** [comment]
Confirmed. It might have something to do with previous filters since its trying to access an app ID from another org.

**Comment by serge17** [comment]
@gmoore @rduran0 Can you try once more please.

**Comment by gmoore** [comment]
@serge17 Thanks I'll take a look tonight.

**Pull request merged**
