### PR TITLE
Contrast 17977 applications filter should only show applications for the selected server

### PR DESCRIPTION
**Pull request by serge17**

### CODE REVIEW

**Comment by SteveFeldman** [comment]
@serge17 is there a dependency on the SDK? I'm getting some odd issues.

**Comment by serge17** [comment]
@SteveFeldman Can you post your logs from building the plugin?

**Comment by SteveFeldman** [comment]
Got it working...issue with the signedJar.

**Comment by SteveFeldman** [comment]
Not seeing the approved button...but I'm good with the change. Very minor. Need to get to all of the other enhancements soon.

**Comment by SteveFeldman** [comment]
@serge17 I believe this is ready to merge.

**Comment by SteveFeldman** [comment]
Ready to merge...

**Pull request merged**
