### PR TITLE
CONTRAST-18329

### PR DESCRIPTION
**Pull request by rduran0**
Updated plugin name and added maven plugin to sign automatically during package phase.

## Notes
* Signing parameters are passed as maven run parameters (See README.md).

### CODE REVIEW

**Comment by SteveFeldman** [comment]
@rduran0 I'm getting the following

`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.496 s]
[INFO] Eclipse Mars Target Definition ..................... SUCCESS [  0.330 s]
[INFO] contrastide.plugins ................................ SUCCESS [  0.008 s]
[INFO] com.contrastsecurity.ide.rest.sdk .................. FAILURE [  1.358 s]
[INFO] com.contrastsecurity.ide.eclipse.core .............. SKIPPED
[INFO] com.contrastsecurity.ide.eclipse.core.tests ........ SKIPPED
[INFO] com.contrastsecurity.ide.eclipse.ui ................ SKIPPED
[INFO] com.contrastsecurity.ide.eclipse.ui.tests .......... SKIPPED
[INFO] contrastide.features ............................... SKIPPED
[INFO] com.contrastsecurity.ide.eclipse.feature ........... SKIPPED
[INFO] Contrast IDE Update Site ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.746 s
[INFO] Finished at: 2017-10-23T21:10:57-04:00
[INFO] Final Memory: 53M/1176M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jarsigner-plugin:1.4:sign (sign) on project com.contrastsecurity.ide.rest.sdk: Failed executing '/bin/sh -c cd /Users/stevefeldman/Projects/ide-plugin-eclipse2/plugins/com.contrastsecurity.ide.rest.sdk && /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/../bin/jarsigner /Users/stevefeldman/Projects/ide-plugin-eclipse2/plugins/com.contrastsecurity.ide.rest.sdk/target/com.contrastsecurity.ide.rest.sdk_1.0.0.v20170928-1551.jar' - exitcode 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-jarsigner-plugin:1.4:sign (sign) on project com.contrastsecurity.ide.rest.sdk: Failed executing '/bin/sh -c cd /Users/stevefeldman/Projects/ide-plugin-eclipse2/plugins/com.contrastsecurity.ide.rest.sdk && /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/../bin/jarsigner /Users/stevefeldman/Projects/ide-plugin-eclipse2/plugins/com.contrastsecurity.ide.rest.sdk/target/com.contrastsecurity.ide.rest.sdk_1.0.0.v20170928-1551.jar' - exitcode 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed executing '/bin/sh -c cd /Users/stevefeldman/Projects/ide-plugin-eclipse2/plugins/com.contrastsecurity.ide.rest.sdk && /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/../bin/jarsigner /Users/stevefeldman/Projects/ide-plugin-eclipse2/plugins/com.contrastsecurity.ide.rest.sdk/target/com.contrastsecurity.ide.rest.sdk_1.0.0.v20170928-1551.jar' - exitcode 1
	at org.apache.maven.plugins.jarsigner.AbstractJarsignerMojo.processArchive(AbstractJarsignerMojo.java:515)
	at org.apache.maven.plugins.jarsigner.AbstractJarsignerMojo.processArtifact(AbstractJarsignerMojo.java:430)
	at org.apache.maven.plugins.jarsigner.AbstractJarsignerMojo.execute(AbstractJarsignerMojo.java:279)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.contrastsecurity.ide.rest.sdk
Steves-MacBook-Pro:ide-plugin-eclipse2 stevefeldman$ 
`

**Comment by SteveFeldman** [comment]
OK @rduran0 I see what's going on. You are skipping jar signing in your travis.yml file (-Djarsigner.skip=true). How come?

**Comment by SteveFeldman** [comment]
@rduran0 I'm good with this PR, however will package signing happen from the Jenkins job or do we need another PR on the travis config?

**Comment by rduran0** [comment]
@SteveFeldman I updated the README.md with an example of the maven command with signing parameters. Jenkins build should work okay if it includes those parameters. We could include signing with the Travis build if its required, we just need to create environment variables for all values required for the keytool command to create a keystore for the signing.

**Comment by SteveFeldman** [comment]
@rduran0 please merge and work with @meg23 to get this deployed.

**Pull request merged**
