### PR TITLE
Contrast 19389 tagging from details view

### PR DESCRIPTION
**Pull request by serge17**

### CODE REVIEW

**Comment by SteveFeldman** [comment]
@serge17 looks like the box is not showing multiple tags all that well. I'm looking at a vuln with 5+ tags and all I can see is 1 at a time, then scroll. Can you expand the list by changing the height of the pop-up? Let's get it to 5 before scrolling.

**Comment by serge17** [comment]
@SteveFeldman Done.

**Comment by SteveFeldman** [comment]
There are two issues...

1. Add one of the existing tags and you get them all. In my example, I had about 10-12 available tags. I clicked on the first one and then all of the available tags were added.

2. The width is off. We need a few more pixels to the right. See how the dialogue is off.

screen shot 2018-01-04 at 10 36 22 pm
screen shot 2018-01-04 at 10 34 59 pm

**Comment by rduran0** [comment]
I tried the tagging functionality and I noticed that if you made a change in the TeamServer, new or removed tags wouldn't reflect on the plugin UI. Perhaps is due to the cache. I think you should still request for the current tags just to verify if there were any changes made from TeamServer or another plugin.

**Comment by serge17** [comment]
@SteveFeldman I think the first issue could be caused by mouse wheel selection. Now it is disabled. I have also increased the width of the dialog.
@rduran0 Yes, that is because of the caching. There is no way to fix it. It also happens for the rest of trace data, such as status changes.

**Comment by SteveFeldman** [comment]
@serge17 I've rebuilt...relaunched...etc...still seeing the issue with all of the tags being added.

**Comment by serge17** [comment]
@SteveFeldman Can you try now please

**Comment by SteveFeldman** [comment]
Functionally everything is working without issues. Two minor UI issues left.

1. Can you center the X in the column to remove?
2. What is the column to the right of the X for?

screen shot 2018-01-05 at 9 07 36 pm

**Comment by serge17** [comment]
@SteveFeldman The remove column is now centered. The space on the right side of the table is added by default to fill the empty space in all tables.

**Pull request merged**
