### PR TITLE
CONTRAST-14411

### PR DESCRIPTION
**Pull request by rduran0**
- Implemented support for searching more type of files (non-java files).
- Implemented functionality that allows the user go to vulnerability details Event tab when double clicking over the Severity or Vulnerability column.

## Notes

- This is only valid for those kind of stacktrace lines that have an extension and a line number.
- Those stacktrace lines without extension or line number, will keep throwing an error message.
- This does not change behavior when the requested file from the stacktrace line its not in your workspace (i.e. dependency classes).

### CODE REVIEW

**Comment by serge17** [comment]
Right now, if there are more than 1 file with the same name, the first occurrence is returned. It is better to return all the found files or restrict the search in some way.

**Comment by rduran0** [comment]
There can be 3 solutions to this in that case:

1. Allow to search for all matches and open an editor for each one.
2. Add a new section in preferences to restrict search, which might even include number 1.
3. Attempt to let Eclipse Search plugin handle the searching and results, although this one might not support opening editors on the required line number.
imagen

4. I could also try to reproduce the Eclipse search plugin layout to show all coincidences too, but this might take much more time.

**Comment by SteveFeldman** [comment]
@rduran0 I can only build this with -DskipTests.

Also getting build errors. We can review when we get online.

**Comment by rduran0** [comment]
The double click functionality over Severity and Vulnerability columns was added. Now when double clicking over a stacttrace line it should open all the found matches (only valid for non-java files).

**Pull request merged**
