### PR TITLE
Contrast 19386 remediation from details view

### PR DESCRIPTION
**Pull request by rduran0**
Implemented behavior similar to TeamServer to change the vulnerability status:

* Added popup with the status changes. Includes comments option at the end.
* If "Not a problem" status is chosen, a dialog will open for the user to specify the reason and some notes (optional).
* Whenever the comments option is enabled, a dialog will open to include them.
* The current vulnerability status is reflected on the button.

### CODE REVIEW

**Comment by SteveFeldman** [comment]
The "enable comments" the way it's implemented does not make sense to me. I think it needs to be visually different. Possibly consider making it a checkbox with a line below the pop-up. 

screen shot 2018-01-08 at 11 03 42 pm

I think the implementation should be consistent with IntelliJ and Visual Studio. This doesn't seem consistent.

**Comment by SteveFeldman** [comment]
I enabled comments and this is what I saw for any status other than "Not a Problem"

See...
screen shot 2018-01-08 at 11 05 21 pm

**Comment by rduran0** [comment]
Oh,....it was supposed to say "Add comments". I'll fix that and see how to change the behavior for the "Enable comments" check.

**Comment by SteveFeldman** [comment]
Just built and I'm seeing this. Notice the text cut off. Also, even when I enable comments, I cannot actually submit the comments.

screen shot 2018-01-09 at 10 31 52 pm

**Comment by rduran0** [comment]
@SteveFeldman  I tried to fix the size and position manually for mac, I suppose the resolution differences are not recalculated automatically by Eclipse using that approach. An easier way to fix it, would be to just change the button text from "Add comments" to "Comment". If changing the string its not an option, I can hide the default window buttons and use custom ones for a more correct display.

Also I'm having problems with changing the behavior for the status popup. It seems the popup views don't have support to actually make the "Enable comments" option to look more like a checkbox. I could also always display the comments window and remove that option or just change the flow to how it is done on IntelliJ instead.

**Comment by SteveFeldman** [comment]
@rduran0 consistency across the 3 implementations is my #1 priority. I would rather see you implement it the way it's been done for IntelliJ.

**Comment by rduran0** [comment]
UI change done.

**Comment by serge17** [comment]
@rduran0 I think it is better to move all the logic out of the Diallog to VulnerabilityDetailsPage. Dialog should be used only to get user input.

**Comment by rduran0** [comment]
@serge17 Request logic was moved to Details page.

**Comment by serge17** [comment]
@rduran0 I think there is no need to add any listener to the Dialog. You just create a dialog class variable
`TraceStatusRequest request;`
Initialize it when "OK" button is pressed.

Then: 
`	private void showMarkStatusDialog(Composite composite) {
		markStatusDialog = new MarkStatusDialog(getShell(), trace.getUuid());
		markStatusDialog.setBlockOnOpen(true);
		markStatusDialog.open();
               markStatusDialog.getTraceStatusRequest();
              if (markStatusDialog.getTraceStatusRequest() != null){
                        make request
               }
	}
`

**Comment by rduran0** [comment]
Ok @serge17, I'll use that approach and add somekind of progress indicator.

**Pull request merged**
